from __future__ import annotations

from typing import TypeAlias

TokenLeaf: TypeAlias = str | int | float
TokenNode: TypeAlias = TokenLeaf | "TokenMap"
TokenMap: TypeAlias = dict[str, TokenNode]

TOKENS: TokenMap = {
    "color": {
        "primitive": {
            "white": "#FFFFFF",
            "off_white": "#FAFAF8",
            "warm_white": "#FFFEF7",
            "black": "#0D0D0D",
            "charcoal": "#1A1A1A",
            "dark_gray": "#333333",
            "gray_700": "#555555",
            "gray_500": "#888888",
            "gray_300": "#CCCCCC",
            "gray_200": "#E0E0E0",
            "gray_100": "#F2F2F2",
            "gray_50": "#F7F7F7",
            "red": "#D94F4F",
            "navy": "#003087",
            "cobalt": "#1B4FD8",
            "burgundy": "#8B0000",
            "editorial_red": "#C41E3A",
            "forest": "#2D5016",
            "teal": "#0D7377",
            "amber": "#B8860B",
        },
        "semantic": {
            "bg": "#FFFFFF",
            "surface": "#F7F7F7",
            "text": "#1A1A1A",
            "text_secondary": "#555555",
            "text_muted": "#888888",
            "accent": "#D94F4F",
            "accent_subtle": "#FFF0F0",
            "border": "#E0E0E0",
            "border_light": "#F2F2F2",
            "divider": "#E0E0E0",
        },
        "component": {
            "kpi_value": "#1A1A1A",
            "kpi_label": "#555555",
            "kpi_delta": "#888888",
            "kpi_accent_border": "#D94F4F",
            "bar_fill_default": "#D0D0D0",
            "bar_fill_max": "#1A1A1A",
            "bar_fill_accent": "#D94F4F",
            "bar_track": "#F2F2F2",
            "bar_label": "#555555",
            "bar_value": "#1A1A1A",
            "donut_legend": "#555555",
            "compare_left_bg": "#F7F7F7",
            "compare_right_bg": "#FFFFFF",
            "compare_divider_text": "#CCCCCC",
            "compare_divider_line": "#E8E8E8",
            "compare_bullet_default": "#CCCCCC",
            "compare_bullet_accent": "#D94F4F",
        },
    },
    "typography": {
        "font_stack": {
            "primary": "'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', 'Noto Sans KR', Arial, Helvetica, sans-serif",
            "display": "'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', 'Noto Sans KR', Arial, Helvetica, sans-serif",
            "mono": "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
        },
        "scale": {
            "display": 48,
            "title": 36,
            "section": 28,
            "slide_title": 24,
            "body": 18,
            "body_large": 20,
            "caption": 14,
            "footnote": 12,
            "micro": 10,
            "kpi_value": 56,
            "stat_hero": 80,
        },
        "weight": {
            "regular": 400,
            "medium": 500,
            "semibold": 600,
            "bold": 700,
            "black": 900,
        },
        "tracking": {
            "display": -1.5,
            "headline": -0.5,
            "body": 0,
            "caption": 0.3,
            "wide": 2,
        },
        "leading": {
            "tight": 1.1,
            "snug": 1.25,
            "normal": 1.4,
            "relaxed": 1.6,
        },
    },
    "layout": {
        "canvas_width": 1920,
        "canvas_height": 1080,
        "safe_margin_x": 100,
        "safe_margin_top": 220,
        "content_width": 1720,
        "content_height": 760,
        "grid_unit": 8,
        "gutter": 24,
        "section_gap": 32,
    },
    "component": {
        "radius": 2,
        "radius_lg": 4,
        "stroke": 1,
        "stroke_accent": 4,
        "divider_height": 1,
        "card_padding_x": 36,
        "card_padding_y": 40,
        "shadow": "none",
    },
    "editorial": {
        "running_header_size": 9,
        "running_header_opacity": 0.5,
        "folio_size": 10,
        "source_size": 8,
        "exhibit_label_size": 11,
        "caption_size": 12,
        "divider_margin_top": 16,
        "divider_margin_bottom": 24,
    },
}
