from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

DominantElement = Literal["text", "image", "data", "whitespace", "mixed"]
ContentDensity = Literal["sparse", "medium", "dense"]


@dataclass(frozen=True)
class LayoutVariant:
    id: str
    layout_type: str
    variant_key: str
    label: str
    dominant_element: DominantElement
    content_density: ContentDensity
    split_ratio: str | None
    css_overrides: dict[str, str]
    description: str


def _variant(
    *,
    layout_type: str,
    variant_key: str,
    label: str,
    dominant_element: DominantElement,
    content_density: ContentDensity,
    split_ratio: str | None,
    css_overrides: dict[str, str],
    description: str,
) -> LayoutVariant:
    return LayoutVariant(
        id=f"{layout_type}.{variant_key}",
        layout_type=layout_type,
        variant_key=variant_key,
        label=label,
        dominant_element=dominant_element,
        content_density=content_density,
        split_ratio=split_ratio,
        css_overrides=css_overrides,
        description=description,
    )


VARIANTS: dict[str, list[LayoutVariant]] = {
    "title_slide": [
        _variant(
            layout_type="title_slide",
            variant_key="default",
            label="Centered Hero",
            dominant_element="text",
            content_density="sparse",
            split_ratio=None,
            css_overrides={},
            description="Centered title and subtitle with balanced whitespace.",
        ),
        _variant(
            layout_type="title_slide",
            variant_key="editorial_left",
            label="Editorial Left",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "align-items": "flex-start",
                "justify-content": "center",
                "text-align": "left",
                "padding": "0 220px 80px 120px",
                "max-width": "1520px",
            },
            description="Left-anchored title block for an editorial opening posture.",
        ),
        _variant(
            layout_type="title_slide",
            variant_key="cinematic_bottom",
            label="Cinematic Bottom",
            dominant_element="whitespace",
            content_density="sparse",
            split_ratio=None,
            css_overrides={
                "align-items": "flex-start",
                "justify-content": "flex-end",
                "text-align": "left",
                "padding": "0 180px 120px 120px",
                "max-width": "1580px",
            },
            description="Bottom-heavy text zone with a large upper field for cinematic rhythm.",
        ),
    ],
    "section_divider": [
        _variant(
            layout_type="section_divider",
            variant_key="default",
            label="Centered Divider",
            dominant_element="text",
            content_density="sparse",
            split_ratio=None,
            css_overrides={},
            description="Centered section marker matching the baseline divider composition.",
        ),
        _variant(
            layout_type="section_divider",
            variant_key="left_anchored",
            label="Left Anchored Divider",
            dominant_element="whitespace",
            content_density="sparse",
            split_ratio=None,
            css_overrides={
                "align-items": "flex-start",
                "justify-content": "center",
                "text-align": "left",
                "padding": "0 240px 0 120px",
                "max-width": "1500px",
            },
            description="Section label sits left with clear trailing whitespace.",
        ),
        _variant(
            layout_type="section_divider",
            variant_key="number_prefixed",
            label="Number Prefixed Divider",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "align-items": "flex-start",
                "justify-content": "flex-start",
                "text-align": "left",
                "padding": "120px 220px 0 120px",
                "row-gap": "24px",
                "max-width": "1500px",
            },
            description="Top-left section heading with room for a prefixed number like 01 - Strategy.",
        ),
    ],
    "body_text": [
        _variant(
            layout_type="body_text",
            variant_key="default",
            label="Standard Body",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Standard left-aligned body text with title.",
        ),
        _variant(
            layout_type="body_text",
            variant_key="indented",
            label="Indented Body",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={"padding-left": "180px", "max-width": "1400px"},
            description="Indented text block with asymmetric whitespace on the left.",
        ),
        _variant(
            layout_type="body_text",
            variant_key="wide_margin",
            label="Wide Margin Body",
            dominant_element="whitespace",
            content_density="sparse",
            split_ratio=None,
            css_overrides={"padding": "60px 200px 40px 200px", "max-width": "1320px"},
            description="Generous inner margins to emphasize short, high-signal text.",
        ),
    ],
    "two_column": [
        _variant(
            layout_type="two_column",
            variant_key="default",
            label="Balanced 50-50",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="50:50",
            css_overrides={},
            description="Symmetric two-column composition for balanced arguments.",
        ),
        _variant(
            layout_type="two_column",
            variant_key="text_heavy_left",
            label="Text Heavy Left 60-40",
            dominant_element="text",
            content_density="dense",
            split_ratio="60:40",
            css_overrides={
                "--split-ratio": "60:40",
                "column-gap": "40px",
                "padding-right": "80px",
            },
            description="Wider left column for narrative detail, tighter right support lane.",
        ),
        _variant(
            layout_type="two_column",
            variant_key="visual_heavy_right",
            label="Visual Heavy Right 40-60",
            dominant_element="image",
            content_density="medium",
            split_ratio="40:60",
            css_overrides={
                "--split-ratio": "40:60",
                "column-gap": "40px",
                "padding-left": "80px",
            },
            description="Narrow text lane with larger right visual zone for contrast.",
        ),
    ],
    "three_column": [
        _variant(
            layout_type="three_column",
            variant_key="default",
            label="Balanced Three-Up",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="33:33:33",
            css_overrides={},
            description="Even three-column layout for parallel categories.",
        ),
        _variant(
            layout_type="three_column",
            variant_key="lead_column_left",
            label="Lead Left 40-30-30",
            dominant_element="text",
            content_density="dense",
            split_ratio="40:30:30",
            css_overrides={
                "--split-ratio": "40:30:30",
                "column-gap": "28px",
                "padding-right": "40px",
            },
            description="Expanded first column for key message, two support columns to the right.",
        ),
        _variant(
            layout_type="three_column",
            variant_key="center_feature",
            label="Center Feature 30-40-30",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="30:40:30",
            css_overrides={
                "--split-ratio": "30:40:30",
                "column-gap": "24px",
                "padding": "20px 40px",
            },
            description="Middle column leads while side columns provide compact context.",
        ),
    ],
    "image_full": [
        _variant(
            layout_type="image_full",
            variant_key="default",
            label="Full Image Standard",
            dominant_element="image",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Standard full-frame image composition with title-safe spacing.",
        ),
        _variant(
            layout_type="image_full",
            variant_key="with_caption",
            label="Image with Caption Zone",
            dominant_element="image",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "padding": "0 120px 120px 120px",
                "row-gap": "20px",
                "align-items": "flex-end",
            },
            description="Reserves lower space for caption or source while preserving image impact.",
        ),
        _variant(
            layout_type="image_full",
            variant_key="full_bleed",
            label="Safe-Area Full Bleed",
            dominant_element="image",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "padding": "0",
                "width": "1720px",
                "height": "760px",
                "max-width": "1720px",
            },
            description="Image extends to the full content frame edge for maximum visual weight.",
        ),
    ],
    "image_left": [
        _variant(
            layout_type="image_left",
            variant_key="default",
            label="Image Left 60-40",
            dominant_element="image",
            content_density="medium",
            split_ratio="60:40",
            css_overrides={},
            description="Image-led left column with supporting text on the right.",
        ),
        _variant(
            layout_type="image_left",
            variant_key="with_caption",
            label="Image Left with Caption",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="50:50",
            css_overrides={
                "--split-ratio": "50:50",
                "padding-bottom": "64px",
                "row-gap": "16px",
            },
            description="Balances image and text with room for a concise image caption.",
        ),
        _variant(
            layout_type="image_left",
            variant_key="full_bleed",
            label="Image Left Full Bleed",
            dominant_element="image",
            content_density="dense",
            split_ratio="65:35",
            css_overrides={
                "--split-ratio": "65:35",
                "padding-left": "0",
                "padding-right": "80px",
            },
            description="Image pushes to the left content edge for stronger visual pull.",
        ),
    ],
    "image_right": [
        _variant(
            layout_type="image_right",
            variant_key="default",
            label="Image Right 40-60",
            dominant_element="image",
            content_density="medium",
            split_ratio="40:60",
            css_overrides={},
            description="Text-first left lane with dominant right-side image.",
        ),
        _variant(
            layout_type="image_right",
            variant_key="with_caption",
            label="Image Right with Caption",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="50:50",
            css_overrides={
                "--split-ratio": "50:50",
                "padding-bottom": "64px",
                "row-gap": "16px",
            },
            description="Balanced split that keeps room for explanatory caption text.",
        ),
        _variant(
            layout_type="image_right",
            variant_key="full_bleed",
            label="Image Right Full Bleed",
            dominant_element="image",
            content_density="dense",
            split_ratio="35:65",
            css_overrides={
                "--split-ratio": "35:65",
                "padding-right": "0",
                "padding-left": "80px",
            },
            description="Image expands to right edge while text stays in a focused left rail.",
        ),
    ],
    "image_grid": [
        _variant(
            layout_type="image_grid",
            variant_key="default",
            label="Balanced Grid",
            dominant_element="image",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Standard multi-image grid with even spacing.",
        ),
        _variant(
            layout_type="image_grid",
            variant_key="tight_mosaic",
            label="Tight Mosaic",
            dominant_element="image",
            content_density="dense",
            split_ratio=None,
            css_overrides={"gap": "16px", "padding": "8px 0"},
            description="Denser image grouping for high-volume visual evidence.",
        ),
        _variant(
            layout_type="image_grid",
            variant_key="storyboard_strip",
            label="Storyboard Strip",
            dominant_element="image",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "grid-auto-flow": "column",
                "grid-auto-columns": "1fr",
                "gap": "24px",
                "padding": "0 40px 80px 40px",
            },
            description="Horizontal visual sequence that reads like storyboard frames.",
        ),
    ],
    "table_slide": [
        _variant(
            layout_type="table_slide",
            variant_key="default",
            label="Standard Table",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Default table footprint for core tabular reporting.",
        ),
        _variant(
            layout_type="table_slide",
            variant_key="wide_table",
            label="Wide Table",
            dominant_element="data",
            content_density="dense",
            split_ratio=None,
            css_overrides={"padding": "16px 0", "max-width": "1720px"},
            description="Maximizes horizontal room for wider datasets.",
        ),
        _variant(
            layout_type="table_slide",
            variant_key="narrow_focus",
            label="Narrow Focus Table",
            dominant_element="whitespace",
            content_density="sparse",
            split_ratio=None,
            css_overrides={"padding": "20px 140px", "max-width": "1440px"},
            description="Constrained table width for fewer columns and stronger emphasis.",
        ),
    ],
    "code_block": [
        _variant(
            layout_type="code_block",
            variant_key="default",
            label="Standard Code",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Default code block area with balanced margins.",
        ),
        _variant(
            layout_type="code_block",
            variant_key="annotated",
            label="Annotated Code 65-35",
            dominant_element="mixed",
            content_density="dense",
            split_ratio="65:35",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "65% 35%",
                "column-gap": "32px",
                "align-items": "start",
            },
            description="Code area with a right annotation lane for walkthrough context.",
        ),
        _variant(
            layout_type="code_block",
            variant_key="focused_column",
            label="Focused Column",
            dominant_element="text",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "max-width": "1380px",
                "padding-left": "120px",
                "padding-right": "120px",
            },
            description="Narrower code column to improve readability for long lines.",
        ),
    ],
    "blockquote": [
        _variant(
            layout_type="blockquote",
            variant_key="default",
            label="Centered Quote",
            dominant_element="text",
            content_density="sparse",
            split_ratio=None,
            css_overrides={},
            description="Centered quote treatment with broad surrounding whitespace.",
        ),
        _variant(
            layout_type="blockquote",
            variant_key="editorial_left",
            label="Editorial Quote",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "text-align": "left",
                "max-width": "1360px",
                "padding-left": "180px",
            },
            description="Left-set pull quote style with clear reading edge.",
        ),
        _variant(
            layout_type="blockquote",
            variant_key="bottom_pullquote",
            label="Bottom Pull Quote",
            dominant_element="whitespace",
            content_density="sparse",
            split_ratio=None,
            css_overrides={
                "display": "flex",
                "flex-direction": "column",
                "justify-content": "flex-end",
                "text-align": "left",
                "padding": "0 200px 120px 160px",
            },
            description="Quote anchored low to create a cinematic pause in deck pacing.",
        ),
    ],
    "list_slide": [
        _variant(
            layout_type="list_slide",
            variant_key="default",
            label="Standard List",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Single-column list layout with default spacing.",
        ),
        _variant(
            layout_type="list_slide",
            variant_key="compact_dense",
            label="Compact Dense List",
            dominant_element="text",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "max-width": "1480px",
                "padding": "0 80px",
                "row-gap": "12px",
            },
            description="Tighter rhythm for denser bullet structures.",
        ),
        _variant(
            layout_type="list_slide",
            variant_key="split_list",
            label="Split List 50-50",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="50:50",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "1fr 1fr",
                "column-gap": "48px",
                "align-items": "start",
            },
            description="Two-column list flow that shortens scan distance on long lists.",
        ),
    ],
    "comparison": [
        _variant(
            layout_type="comparison",
            variant_key="default",
            label="VS Divider 50-50",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="50:50",
            css_overrides={},
            description="Standard side-by-side comparison around a central divide.",
        ),
        _variant(
            layout_type="comparison",
            variant_key="stacked",
            label="Stacked Top-Bottom",
            dominant_element="text",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "display": "grid",
                "grid-template-rows": "1fr 1fr",
                "row-gap": "24px",
                "padding": "0 120px",
            },
            description="Top-bottom comparison for chronologic before-after storytelling.",
        ),
        _variant(
            layout_type="comparison",
            variant_key="asymmetric",
            label="Asymmetric 60-40",
            dominant_element="mixed",
            content_density="medium",
            split_ratio="60:40",
            css_overrides={
                "--split-ratio": "60:40",
                "column-gap": "32px",
                "padding-right": "60px",
            },
            description="Dominant primary side with compressed secondary counterpoint.",
        ),
    ],
    "timeline": [
        _variant(
            layout_type="timeline",
            variant_key="default",
            label="Horizontal Timeline",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Default linear timeline across the content width.",
        ),
        _variant(
            layout_type="timeline",
            variant_key="vertical_stack",
            label="Vertical Timeline",
            dominant_element="data",
            content_density="dense",
            split_ratio="35:65",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "420px 1fr",
                "column-gap": "48px",
                "align-items": "start",
            },
            description="Date rail on the left with detail blocks stacked on the right.",
        ),
        _variant(
            layout_type="timeline",
            variant_key="milestone_spotlight",
            label="Milestone Spotlight",
            dominant_element="whitespace",
            content_density="sparse",
            split_ratio=None,
            css_overrides={
                "padding": "0 180px 80px 120px",
                "max-width": "1560px",
                "row-gap": "24px",
            },
            description="Selective milestone spacing for a strategic pacing effect.",
        ),
    ],
    "process": [
        _variant(
            layout_type="process",
            variant_key="default",
            label="Standard Process",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Balanced process flow with evenly spaced stages.",
        ),
        _variant(
            layout_type="process",
            variant_key="horizontal_band",
            label="Horizontal Band",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "display": "flex",
                "align-items": "center",
                "justify-content": "space-between",
                "padding": "120px 40px 60px 40px",
            },
            description="Process stages anchored in a horizontal band through mid-canvas.",
        ),
        _variant(
            layout_type="process",
            variant_key="vertical_flow",
            label="Vertical Flow",
            dominant_element="data",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "display": "flex",
                "flex-direction": "column",
                "justify-content": "center",
                "row-gap": "20px",
                "padding": "0 220px",
            },
            description="Top-to-bottom process stack for procedural walkthrough slides.",
        ),
    ],
    "kpi_dashboard": [
        _variant(
            layout_type="kpi_dashboard",
            variant_key="default",
            label="KPI Grid",
            dominant_element="data",
            content_density="dense",
            split_ratio=None,
            css_overrides={},
            description="Default KPI card grid for quick numeric scanning.",
        ),
        _variant(
            layout_type="kpi_dashboard",
            variant_key="horizontal_strip",
            label="Horizontal Strip",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "display": "grid",
                "grid-template-columns": "repeat(4, 1fr)",
                "column-gap": "24px",
                "align-items": "stretch",
                "padding": "220px 0 180px 0",
            },
            description="Single-row KPI strip for a clean scorecard look.",
        ),
        _variant(
            layout_type="kpi_dashboard",
            variant_key="stacked_vertical",
            label="Stacked Vertical",
            dominant_element="data",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "display": "grid",
                "grid-template-columns": "1fr",
                "row-gap": "20px",
                "max-width": "980px",
                "padding-left": "120px",
            },
            description="Vertical KPI stack that prioritizes sequential reading.",
        ),
    ],
    "chart_slide": [
        _variant(
            layout_type="chart_slide",
            variant_key="default",
            label="Standard Chart",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Full-width chart area with default annotation behavior.",
        ),
        _variant(
            layout_type="chart_slide",
            variant_key="with_annotation",
            label="Chart with Annotation 65-35",
            dominant_element="mixed",
            content_density="dense",
            split_ratio="65:35",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "65% 35%",
                "column-gap": "32px",
                "align-items": "start",
            },
            description="Shrinks chart area to add a right analysis panel.",
        ),
        _variant(
            layout_type="chart_slide",
            variant_key="with_insight_bar",
            label="Chart with Insight Bar",
            dominant_element="mixed",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "display": "grid",
                "grid-template-rows": "120px 1fr",
                "row-gap": "24px",
                "padding-top": "72px",
            },
            description="Adds a top insight strip above the chart body.",
        ),
    ],
    "icon_grid": [
        _variant(
            layout_type="icon_grid",
            variant_key="default",
            label="Balanced Icon Grid",
            dominant_element="mixed",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Default icon-and-label grid with even visual rhythm.",
        ),
        _variant(
            layout_type="icon_grid",
            variant_key="left_weighted",
            label="Left Weighted Grid",
            dominant_element="mixed",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "padding-right": "120px",
                "max-width": "1580px",
                "justify-content": "flex-start",
            },
            description="Grid mass shifts left, leaving intentional right-side breathing room.",
        ),
        _variant(
            layout_type="icon_grid",
            variant_key="compact_matrix",
            label="Compact Matrix",
            dominant_element="data",
            content_density="dense",
            split_ratio=None,
            css_overrides={"gap": "16px", "padding": "20px 40px"},
            description="Tighter icon matrix for larger category counts.",
        ),
    ],
    "closing_cta": [
        _variant(
            layout_type="closing_cta",
            variant_key="default",
            label="Centered CTA",
            dominant_element="text",
            content_density="sparse",
            split_ratio=None,
            css_overrides={},
            description="Centered closing message with standard next-step spacing.",
        ),
        _variant(
            layout_type="closing_cta",
            variant_key="action_left",
            label="Action Left",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "text-align": "left",
                "align-items": "flex-start",
                "justify-content": "center",
                "padding": "0 260px 0 120px",
            },
            description="Left-led call to action with an executive memo tone.",
        ),
        _variant(
            layout_type="closing_cta",
            variant_key="next_steps_bottom",
            label="Bottom Steps",
            dominant_element="mixed",
            content_density="sparse",
            split_ratio=None,
            css_overrides={
                "display": "flex",
                "flex-direction": "column",
                "justify-content": "space-between",
                "text-align": "left",
                "padding": "80px 160px 100px 160px",
            },
            description="Primary statement above with operational next steps anchored low.",
        ),
    ],
    "executive_summary": [
        _variant(
            layout_type="executive_summary",
            variant_key="default",
            label="Summary Grid",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Default executive summary with KPI grid and conclusion line.",
        ),
        _variant(
            layout_type="executive_summary",
            variant_key="headline_left",
            label="Headline Left 42-58",
            dominant_element="mixed",
            content_density="dense",
            split_ratio="42:58",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "42% 58%",
                "column-gap": "40px",
                "align-items": "start",
            },
            description="Message headline on left, KPI evidence block on the right.",
        ),
        _variant(
            layout_type="executive_summary",
            variant_key="metric_strip",
            label="Metric Strip",
            dominant_element="data",
            content_density="medium",
            split_ratio=None,
            css_overrides={
                "display": "grid",
                "grid-template-rows": "180px 1fr",
                "row-gap": "24px",
                "padding": "40px 40px 0 40px",
            },
            description="Top metric strip with lower narrative support zone.",
        ),
    ],
    "ai_hint": [
        _variant(
            layout_type="ai_hint",
            variant_key="default",
            label="Standard Hint Block",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Single AI hint block with default spacing and hierarchy.",
        ),
        _variant(
            layout_type="ai_hint",
            variant_key="compact_left",
            label="Compact Left Hint",
            dominant_element="text",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "max-width": "1360px",
                "padding": "0 220px 0 120px",
                "text-align": "left",
            },
            description="Narrow left-anchored hint zone for denser decisions or rules.",
        ),
        _variant(
            layout_type="ai_hint",
            variant_key="split_context",
            label="Hint with Context 60-40",
            dominant_element="mixed",
            content_density="dense",
            split_ratio="60:40",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "60% 40%",
                "column-gap": "32px",
                "align-items": "start",
            },
            description="Hint panel paired with right-side context or rationale column.",
        ),
    ],
    "appendix": [
        _variant(
            layout_type="appendix",
            variant_key="default",
            label="Standard Appendix",
            dominant_element="text",
            content_density="medium",
            split_ratio=None,
            css_overrides={},
            description="Default appendix layout for supplemental material.",
        ),
        _variant(
            layout_type="appendix",
            variant_key="dense_index",
            label="Dense Appendix Index",
            dominant_element="text",
            content_density="dense",
            split_ratio=None,
            css_overrides={
                "display": "grid",
                "grid-template-columns": "1fr",
                "row-gap": "12px",
                "padding": "0 60px",
            },
            description="Condensed single-column appendix index for many references.",
        ),
        _variant(
            layout_type="appendix",
            variant_key="two_column_index",
            label="Two-Column Appendix",
            dominant_element="mixed",
            content_density="dense",
            split_ratio="50:50",
            css_overrides={
                "display": "grid",
                "grid-template-columns": "1fr 1fr",
                "column-gap": "48px",
                "align-items": "start",
            },
            description="Two-column index for broad appendix inventories.",
        ),
    ],
}

LAYOUT_TYPES: tuple[str, ...] = tuple(VARIANTS.keys())
VARIANT_BY_ID: dict[str, LayoutVariant] = {
    variant.id: variant
    for variant_list in VARIANTS.values()
    for variant in variant_list
}
DEFAULT_VARIANT: LayoutVariant = VARIANTS["body_text"][0]
